# Generated by Django 4.1.3 on 2023-01-02 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpposingTeam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_number', models.IntegerField(blank=True, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=200, unique=True)),
                ('team_school', models.CharField(blank=True, max_length=200)),
                ('team_contact', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutingReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('autonomous_scoring', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2)),
                ('autonomous_cone_placement', models.CharField(blank=True, choices=[('Station', 'Station'), ('Junction', 'Junctions'), ('Pole', 'Pole'), ('High Pole', 'High Pole')], max_length=12)),
                ('parked_autonomously', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2)),
                ('clear_out_wait_time', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2)),
                ('side_cone_stacks', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2)),
                ('cone_stacks_level', models.CharField(blank=True, choices=[('Floor', 'Floor'), ('Low', 'Low Level'), ('Medium', 'Medium Level'), ('High', 'High Level')], max_length=10)),
                ('circuit_completed', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting_reports.opposingteam', to_field='team_name')),
            ],
        ),
    ]
