# Generated by Django 4.1.3 on 2023-01-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting_reports', '0002_scoutingreport_scoring_cap_placed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opposingteam',
            options={'ordering': ['team_number']},
        ),
    ]
