# Generated by Django 4.1.3 on 2023-01-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_alter_users_first_name_alter_users_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaries',
            name='subteam',
        ),
    ]
