# Generated by Django 4.1.3 on 2023-01-03 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_remove_summaries_subteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summaries',
        ),
    ]
