# Generated by Django 4.1.3 on 2023-01-02 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subteam', models.CharField(choices=[('CD', 'Coding'), ('EG', 'Engineering'), ('DT', 'Drivetrain'), ('SP', 'Spirit')], default='EG', max_length=2)),
                ('summary_date', models.DateField(default=datetime.date.today)),
                ('daily_goal', models.TextField(blank=True)),
                ('work_accomplished', models.TextField(blank=True)),
                ('challenges_faced', models.TextField(blank=True)),
                ('tomorrow_goal', models.CharField(blank=True, max_length=500)),
                ('build_summary_image', models.ImageField(blank=True, upload_to='build_images')),
            ],
        ),
    ]
