# Generated by Django 4.1.3 on 2023-01-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildsummary',
            name='tomorrow_goal',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
