# Generated by Django 4.1.3 on 2023-01-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_summaries', '0002_alter_buildsummary_tomorrow_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildsummary',
            name='tomorrow_goal',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
