# Generated by Django 4.1.3 on 2023-01-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_summaries', '0003_alter_buildsummary_tomorrow_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsummary',
            name='performance_description',
            field=models.TextField(blank=True),
        ),
    ]
