# Generated by Django 4.1.3 on 2023-01-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_summaries', '0004_buildsummary_performance_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildsummary',
            name='performance_description',
        ),
    ]
